Better interaction with non-extractable neighbour inventories
GregTechCE/GregTech pull request #1290
Opened 2020-11-01 00:22 UTC by fmarceau

What:
Based on #1239, implements items 1 and 2 from recommended steps from @LAGIdiot.

Outcome:
Added label in Storage Tab of the Crafting Station to better inform the player
Non-extractable items won't appear in the inventory list of the Crafting Storage's Storage Tab

Note: this is not closing the issue as an upcoming PR will be required to do so

2020-11-01 09:05 UTC, LAGIdiot commented
Thanks for your hard work on this PR. Is this like finished implementation of 1 and 2 from #1239 or are expected changes to it?

As there is problem with shown and extractable amount of items.

In setup where I have **Crafting Station** with **64** and **Forestry:Worktable** with **32** beside it. Storage tab shows **96** even if only **64** is extractable. It shows correct amount in case that there is none of that item in extractable inventories

Setup in pictures:
![2020-11-01_08 57 44](https://user-images.githubusercontent.com/3093101/97797873-09de6380-1c21-11eb-8686-229679727464.png)
![2020-11-01_08 57 47](https://user-images.githubusercontent.com/3093101/97797874-0a76fa00-1c21-11eb-93ef-e0059093ecdd.png)
![2020-11-01_08 57 42](https://user-images.githubusercontent.com/3093101/97797872-08ad3680-1c21-11eb-9de4-f670bcfcc06c.png)

2020-11-03 01:07 UTC, fmarceau commented
@LAGIdiot that wasn't 100% ready but thank you for testing it and finding this issue. I have pushed a fix for it. I also spent more time testing it and everything looks fine. Being new to modded minecraft programming makes it hard to test the code that I wrote as I am not 100% sure what to expect. I did my best :)

2020-11-05 17:56 UTC, LAGIdiot requested changes
Thank you for updating this PR. I did not find any problem when testing, There are just two small comments that requires your attention.

2020-11-05 17:56 UTC, LAGIdiot commented on src/main/java/gregtech/common/inventory/itemsource/ItemSourceList.java
> +            }).collect(Collectors.toSet());
Is this change still required?

2020-11-05 17:56 UTC, LAGIdiot commented on src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityWorkbench.java
> +        widgetGroup.addWidget(new ItemListGridWidget(2, 47, 9, 5, itemList));
Please move this little bit up so space between this and player inventory is same as space between Crafting Station inventory and player inventory on other tab page.

2020-11-07 08:05 UTC, LAGIdiot requested changes
Thanks for your hard work on this PR. I have one more question/request regarding this.

2020-11-07 08:05 UTC, LAGIdiot commented on src/main/java/gregtech/common/inventory/itemsource/ItemSourceList.java
> +import java.util.stream.Collectors;
Are these newly added imports still required? If not please remove them.

2020-11-08 12:54 UTC, LAGIdiot commented
I have marked #1239  to be closed by this as partial mitigation of problem before we have full-size solution from #1302

2020-11-23 17:11 UTC, LAGIdiot commented on src/main/java/gregtech/common/inventory/itemsource/ItemSourceList.java
> +import java.util.stream.Collectors;
```suggestion
import net.minecraft.util.ITickable;
import net.minecraft.world.World;

import javax.annotation.Nullable;
import java.util.*;
import java.util.concurrent.CopyOnWriteArrayList;
```

2020-11-23 17:14 UTC, merged