Fix the Primitive Blast Furnace Voiding outputs
GregTechCE/GregTech pull request #1351
Opened 2020-12-16 04:14 UTC by ALongStringOfNumbers

**What:**
After the latest version of GTCE (1.10.8.599) was released, it was noticed that the Primitive Blast Furnace was voiding both the steel and the ashes outputs when the ash output in the output slot was too high and thus the recipe outputs could not be merged into the output slots

**How solved:**
Since the PBF is somewhat special and checks for room based on only the recipe outputs (not including the ash), and then adds the ash outputs after, there were issues with the outputs voiding. The PBF has been updated to check for available room based both on the ash generated and the recipe outputs now. This means that the recipe will not function if there is not room in the output slots for both, instead of the previous behavior of voiding the ash generated by the recipe if there was not room for the ash. If this behavior (voiding the ash) is desired, I can attempt to replicate that behavior.

**Outcome:**
Fixes recipe outputs being voided in the Primitive Blast Furnace if one output slot was full

_Please fill in as much useful information as possible. Also please remove all unused sections._

2020-12-18 11:51 UTC, LAGIdiot reviewed
This seems strange. If I understand it correctly when there is no place for ashes just produce main output? That should not be like that. It should be if there is not enough space for both then don't produce right?

2020-12-18 11:59 UTC, LAGIdiot commented
Sorry I did not finished reading you PR opening comment and go straight to code. So you can skip my first comment.

I think this should have been open as bug first when we could iron out that question regarding ash voiding so you don't have to change implementation (no you don't have to open bug now).

Anyway for situation when ash is full but there is still space for steel then it should not process as we don't want any voiding.

2020-12-18 12:00 UTC, LAGIdiot requested changes
Please update as per my last comment

2020-12-18 14:38 UTC, ALongStringOfNumbers commented
Ok, the PR has been updated to no longer void the ash when it reaches near maximum stack size, instead the PBF will stop until the outputs are cleared from it. I will suggest though that maybe the PBF needs another output slot now.

2021-01-07 17:29 UTC, LAGIdiot approved these changes
Thanks for finishing this PR.

2021-01-11 17:32 UTC, merged