Fix Turbine Running When It Shouldn't
GregTechCE/GregTech pull request #1422
Opened 2021-01-25 03:11 UTC by DStrand1

**What:**
Fixes the bug demonstrated by Issue #1367 
Additionally fixes the bug that when the Turbine multiblock invalidated, the rotor speed is not reset.

**How solved:**
I added a check to the RotorHolder to check if it has a rotor in its inventory, and reset speed and disable controller if not. I also had to add a handful of checks around to get all the edge cases ironed out, since `FuelRecipeLogic` was not able to properly check for the secondary condition of having a rotor present, so I had to override it. There was also an issue where setting the controller to inactive didn't reset the current recipe's processing time. I couldn't set the multiblock to inactive in the rotor holder, since there was a problem where `MetaTileEntityMultiblockPart::getController()` was returning null on world load, causing the turbine speed to be reset on a relog.

**Outcome:**
Closes #1367

**Possible compatibility issue:**
This code brought up an edge case where when the Controller block itself was broken, the rotor speed was not reset since the lower level class `MultiblockControllerBase` was not calling `invalidateStructure()` directly, but instead simply removing each part from the multiblock. I'm not sure of the reasoning of this, but if this fix is reverting a purposeful design decision, it can be reverted. I left the old code in a comment in that file. If reverted, it would only mean that the rotor speed wouldn't be reset when specifically the controller was broken, but it may have other implications.

2021-01-30 10:53 UTC, LAGIdiot requested changes
Thanks for submitting this PR. There are few areas which needs to be changed.

2021-01-30 10:53 UTC, LAGIdiot commented on src/main/java/gregtech/common/metatileentities/multi/electric/generator/MetaTileEntityLargeTurbine.java
> +        getAbilities(ABILITY_ROTOR_HOLDER).get(0).resetRotorSpeed();
Please make public function in class which will provide rotor so that it is easily accessible

2021-01-30 10:53 UTC, LAGIdiot commented on src/main/java/gregtech/api/capability/impl/FuelRecipeLogic.java
> +            recipeDurationLeft = 0;
No need to check for `recipeDurationLeft` you can just set it

2021-01-30 10:53 UTC, LAGIdiot commented on src/main/java/gregtech/api/metatileentity/multiblock/MultiblockControllerBase.java
> +            invalidateStructure();
I feel that calling `invalidateStructure` is correct move here

2021-01-31 01:47 UTC, DStrand1 commented
Alright, requested changes have been implemented.

2021-01-31 08:25 UTC, LAGIdiot approved these changes
Thanks for finishing this up.

2021-02-08 18:01 UTC, merged