Mechanism to copy text to the player's clipboard
GregTechCE/GregTech pull request #1465
Opened 2021-02-13 22:34 UTC by warjort

**What:**
Add a generic mechanism to copy text to the player's clipboard and use it in the "gt util hand" command for the metavalueitem's name

**How solved:**
Created a new gregtech.api.net.PacketClipboard which is just a for a string.

Added 2 new util methods
GTUtility.copyToClipboard(String) - copies the string to the clipboard if the AWT desktop is available
GTUtility.copyToClipboard(EntityPlayerMP, String) - sends the network packet to the client which will invoke the other method

When "/gt util hand" sends the chat message to display the MetaValueItem.unlocalizedName it now also sends that value to the player's clipboard

**Outcome:**
Closes #1391

2021-02-16 20:11 UTC, LAGIdiot requested changes
Good work on this PR.

Please move all newly added content from `GTUtility` to `ClipboardUtil` so it is in own file.

2021-02-16 23:26 UTC, warjort commented
Done

2021-02-18 20:12 UTC, LAGIdiot requested changes
Thanks for updating this PR. I have find one small thing which needs to be fixed.

2021-02-18 20:12 UTC, LAGIdiot commented on src/main/java/gregtech/api/util/GTUtility.java
> +
Please don't do unnecessary changes to files which are not directly related to given changes.

I know you were touching this file in previous commits but right now there is no to touch this file now.

2021-02-18 21:17 UTC, LAGIdiot approved these changes
Thank you for finishing this up.

2021-02-22 19:33 UTC, merged

2021-02-23 18:01 UTC, LAGIdiot commented
@warjort this should work every time or is there some specific case when this does not work?

2021-02-23 18:36 UTC, warjort commented
It only copies to the clipboard when MetaValueItem.unlocalizedName is sent to chat.
Not all blocks do that.

2021-02-23 18:44 UTC, LAGIdiot commented
Oh I see, thanks for info.