made Rotor holder independant from large turbine controller
GregTechCE/GregTech pull request #1527
Opened 2021-03-12 12:45 UTC by galyfray

**What:**
Implement #1425 

**How solved:**
Create new abstract type `TurbineMultiblockController` which extend the `FueledMultiblockController` and refactor code to make the Rotor holder depending on this class.
added two methods `getRotorIncrementSpeed()` and `getRotorDecrementSpeed()` allowing the variation of the rotor speed to not be hard coded.

**Outcome:**
make `MetaTileEntityRotorHolder` depend on `TurbineMultiblockController` instead of `MetaTileEntityLargeTurbine`

**Additional info:**
Multiblocks using turbines are assumed to be energy producer changing this mean recoding some part  of `FueledMultiblockController` in `MetaTileEntityLargeTurbine` or adding another abstract type in between. 
As both options (implemented and presented ) seems good to me tell me if you found that one way is better than another.

**Possible compatibility issue:**
None

2021-03-12 18:03 UTC, DStrand1 commented
I think that the new parent class should be named `RotorHolderMultiblockController`, or something like it, since as it is, it may not technically be connected to the Turbine anymore, it still looks like it is from class names alone. This way it would be clearer to addons that this class is free game to use for new multiblocks.

2021-03-12 18:14 UTC, galyfray commented
yeah the current name is not really good I'll change it

2021-03-21 12:20 UTC, LAGIdiot requested changes
Good work on this PR. That extraction looks solid there is just few comments mostly regarding naming.

2021-03-21 12:20 UTC, LAGIdiot commented on src/main/java/gregtech/common/metatileentities/multi/electric/generator/TurbineMultiblockController.java
> +public abstract class TurbineMultiblockController extends FueledMultiblockController {
In this case more universal name would be better as it does not have to be tied with Turbine anymore.

2021-03-21 12:20 UTC, LAGIdiot commented on src/main/java/gregtech/common/metatileentities/multi/electric/generator/TurbineMultiblockController.java
> +    public abstract int getRotorIncrementSpeed();
Here it would make more sense to me to use wording `getRotorSpeedIncrement` similarly for decrement

2021-03-21 12:20 UTC, LAGIdiot commented on src/main/java/gregtech/common/metatileentities/multi/electric/generator/TurbineMultiblockController.java
> +    }
Naming here should be more universal too. But there is one implication, we need to provide function with this name on `MetaTileEntityLargeTurbine` level (with just call to this and marked as obsolete) for compatibility reasons.

2021-03-22 21:33 UTC, galyfray commented on src/main/java/gregtech/common/metatileentities/electric/multiblockpart/MetaTileEntityRotorHolder.java
> +                incrementSpeed( maxRotorSpeed/10);
Fixed this even if I'm not comfortable with potential NPE that could be caused by interaction with other mods like Mekanism cardboard boxes

2021-03-22 22:20 UTC, LAGIdiot approved these changes
Thanks for finishing this up

2021-03-22 22:20 UTC, merged