Swap RECIPE_MAPS to protected rather than private
GregTechCE/GregTech pull request #1651
Opened 2021-06-02 22:15 UTC by bruberu

**What:**
This PR is a one-line change that makes RECIPE_MAPS in RecipeMap protected. Before, if one wanted to create a custom JEI wrapper for a recipe map that extended this, they would have no way to prevent the default GTCE wrapper from being put into a category.

**How solved:**
This problem is easily solved by changing the access of RECIPE_MAPS to protected, which allows for subclasses to delete themselves from that list, thus preventing those default wrappers and categories from being registered in the first place.

**Outcome:**
Swaps RECIPE_MAPS instance variable to a protected, rather than private status.

**Possible compatibility issue:**
Since this particular variable wasn't even accessible before, it would be literally impossible for this to create any compatibility issues in the first place.

2021-06-02 22:33 UTC, DStrand1 requested changes
I suggest reworking this PR somewhat, and keeping that List private, so that we can guarantee that it will have all RecipeMaps in it, but instead having an `isHidden` field that is checked when adding the JEI category instead. That way we can guarantee that the List has all maps, and still achieve what you desire, and even more if we ever want a fully hidden RecipeMap for whatever reason.

2021-06-02 22:41 UTC, bruberu commented
I have just addressed those changes, by making said field `isHidden` that is checked before creating a default RecipeMapCategory. I have also created another constructor for RecipeMap to allow for immediately accessing it, while sustaining the original to keep compatibility. I also set the access back to private, and so the outcome should technically now be "RecipeMaps may now have their categories hidden in JEI" instead.

2021-06-03 00:02 UTC, DStrand1 approved these changes
Just one little thing to change, otherwise this PR is good to me.

Also, the force push I did was to cleanup git hierarchy issues at the request of @bruberu.

2021-06-03 00:02 UTC, DStrand1 commented on src/main/java/gregtech/api/recipes/RecipeMap.java
> +    public boolean isHidden = false;
Since this is just a constructor parameter, it may as well be private

2021-06-03 00:04 UTC, DStrand1 commented on src/main/java/gregtech/api/recipes/RecipeMap.java
> +    public boolean isHidden = false;
final*, apologies

2021-06-03 00:27 UTC, DStrand1 approved these changes

2021-06-03 00:28 UTC, DStrand1 commented
Git hierarchy will need to cleaned up again before merge, which I can do later if need be.

2021-06-03 01:10 UTC, bruberu commented
I think I'm going to have to make a new fork, unfortunately, as well as a new PR in order to resolve the git issues.

2021-06-03 01:10 UTC, closed without merging